[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP235XA"
# runner = "elf2uf2-rs -d"
runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
WIFI_NETWORK = "RURSIMA"
WIFI_PASSWORD = "jasammalisima123"
WIFI_USE_STATIC = "true"
# WIFI_NETWORK = "G3"
# WIFI_PASSWORD = "g3radionica.123"
# DEFMT_LOG = "debug"
